name: cd
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: cd
    runs-on: ubuntu-latest
    strategy:
      max-concurrency: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup cdk
        run: |
          npm install -g aws-cdk@2.58.1
      - name: Setup Python dependencies
        run: |
          pip install -r requirements.txt
      - name: CDK Deploy
        run: |
          cdk deploy --require-approval never
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          AWS_CDK_ACCOUNT_ID: ${{ secrets.AWS_CDK_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
